services:
  ddns:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      INFOMANIAK_DDNS_HOSTNAME: "${INFOMANIAK_DDNS_HOSTNAME_ENV}"
      INFOMANIAK_DDNS_USERNAME: "${INFOMANIAK_DDNS_USERNAME_ENV}"
      INFOMANIAK_DDNS_PASSWORD: "${INFOMANIAK_DDNS_PASSWORD_ENV}"
      DDNS_INTERVAL_SECONDS: "300"
      DDNS_ENABLE_IPV6: "false"
      PYTHONUNBUFFERED: "1"

    network_mode: host
