services:
  ddns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddns-infomaniak
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    network_mode: host
